server.port=8081
spring.datasource.url=jdbc:h2:mem:scoutbr
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
apifootball.token=7ff723eb1cd87fc57c11a5d2d85313fd476a6619416bec943b273838300aaa7a
spring.jpa.open-in-view=false